plugins {
    id 'antlr'
}

eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"
  implementation "org.recast4j:recast:1.5.7"
  implementation "org.recast4j:detour:1.5.7"

  antlr "org.antlr:antlr4:4.13.2"
  implementation "org.antlr:antlr4-runtime:4.13.2"
}

tasks.register('converter', JavaExec) {
  group = 'jvm-dungeon-crawler'
  description = 'Print all RON files from Veloren directory (see :core:converter --args="help")'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'io.github.jvmdc.converter.Converter'
  workingDir = rootProject.projectDir
}

// gradlew.bat :core:generateGrammarSource
generateGrammarSource {
  arguments = ["-visitor"]
}